//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpsteinsMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSteps
    {
        public int StepID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> StepNumber { get; set; }
        public string Description { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
